// src/mockData.ts
import { YieldOpportunity } from "./types";

export const mockYieldOpportunities: YieldOpportunity[] = [
  {
    id: "1",
    name: "USDC Lending on Aave",
    estimatedApy: "4.5%",
    network: "Ethereum",
    tvl: "$500M",
    relativeRisk: "Low",
    notes: "Lending USDC on Aave protocol",
    category: "stablecoin",
    link: "https://app.aave.com/",
    isBenchmark: true,
    dateAdded: "2023-09-01T00:00:00.000Z",
  },
  {
    id: "2",
    name: "DAI-USDC LP on Curve",
    estimatedApy: "3.8%",
    network: "Polygon",
    tvl: "$200M",
    relativeRisk: "Low",
    notes: "Providing liquidity for DAI-USDC pool on Curve",
    category: "stablecoin",
    link: "https://curve.fi/",
    isBenchmark: false,
    dateAdded: "2023-09-15T00:00:00.000Z",
  },
  {
    id: "3",
    name: "ETH Staking on Lido",
    estimatedApy: "5.2%",
    network: "Ethereum",
    tvl: "$1B",
    relativeRisk: "Medium",
    notes: "Staking ETH through Lido for stETH",
    category: "volatileAsset",
    link: "https://lido.fi/",
    isBenchmark: true,
    dateAdded: "2023-08-20T00:00:00.000Z",
  },
  {
    id: "4",
    name: "BTC Lending on Compound",
    estimatedApy: "2.8%",
    network: "Ethereum",
    tvl: "$300M",
    relativeRisk: "Medium",
    notes: "Lending BTC (WBTC) on Compound protocol",
    category: "volatileAsset",
    link: "https://compound.finance/",
    isBenchmark: false,
    dateAdded: "2023-09-10T00:00:00.000Z",
  },
  {
    id: "5",
    name: "ETH-USDT LP on Uniswap V3",
    estimatedApy: "15%",
    network: "Ethereum",
    tvl: "$50M",
    relativeRisk: "High",
    notes: "Concentrated liquidity provision for ETH-USDT on Uniswap V3",
    category: "advancedStrategies",
    link: "https://app.uniswap.org/",
    isBenchmark: true,
    dateAdded: "2023-09-05T00:00:00.000Z",
  },
  {
    id: "6",
    name: "Delta Neutral AAVE-ETH Strategy",
    estimatedApy: "12%",
    network: "Ethereum",
    tvl: "$20M",
    relativeRisk: "High",
    notes: "Delta neutral strategy using AAVE and ETH with leveraged positions",
    category: "advancedStrategies",
    link: "https://app.aave.com/",
    isBenchmark: false,
    dateAdded: "2023-09-18T00:00:00.000Z",
  },
];
